// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sql.proto

package util

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type IdInfo struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IdInfo) Reset()         { *m = IdInfo{} }
func (m *IdInfo) String() string { return proto.CompactTextString(m) }
func (*IdInfo) ProtoMessage()    {}
func (*IdInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_698b595ef5cec090, []int{0}
}

func (m *IdInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdInfo.Unmarshal(m, b)
}
func (m *IdInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdInfo.Marshal(b, m, deterministic)
}
func (m *IdInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdInfo.Merge(m, src)
}
func (m *IdInfo) XXX_Size() int {
	return xxx_messageInfo_IdInfo.Size(m)
}
func (m *IdInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_IdInfo.DiscardUnknown(m)
}

var xxx_messageInfo_IdInfo proto.InternalMessageInfo

func (m *IdInfo) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type UserRes struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Data                 *SqlInfo `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRes) Reset()         { *m = UserRes{} }
func (m *UserRes) String() string { return proto.CompactTextString(m) }
func (*UserRes) ProtoMessage()    {}
func (*UserRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_698b595ef5cec090, []int{1}
}

func (m *UserRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRes.Unmarshal(m, b)
}
func (m *UserRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRes.Marshal(b, m, deterministic)
}
func (m *UserRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRes.Merge(m, src)
}
func (m *UserRes) XXX_Size() int {
	return xxx_messageInfo_UserRes.Size(m)
}
func (m *UserRes) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRes.DiscardUnknown(m)
}

var xxx_messageInfo_UserRes proto.InternalMessageInfo

func (m *UserRes) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *UserRes) GetData() *SqlInfo {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *UserRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

//新增
type SqlDetail struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age                  string   `protobuf:"bytes,2,opt,name=age,proto3" json:"age,omitempty"`
	Desc                 string   `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SqlDetail) Reset()         { *m = SqlDetail{} }
func (m *SqlDetail) String() string { return proto.CompactTextString(m) }
func (*SqlDetail) ProtoMessage()    {}
func (*SqlDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_698b595ef5cec090, []int{2}
}

func (m *SqlDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SqlDetail.Unmarshal(m, b)
}
func (m *SqlDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SqlDetail.Marshal(b, m, deterministic)
}
func (m *SqlDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SqlDetail.Merge(m, src)
}
func (m *SqlDetail) XXX_Size() int {
	return xxx_messageInfo_SqlDetail.Size(m)
}
func (m *SqlDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_SqlDetail.DiscardUnknown(m)
}

var xxx_messageInfo_SqlDetail proto.InternalMessageInfo

func (m *SqlDetail) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SqlDetail) GetAge() string {
	if m != nil {
		return m.Age
	}
	return ""
}

func (m *SqlDetail) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

//查询某个的response,删除某个的response,均可通过 ID 进行操作。
type SqlOne struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Data                 *SqlInfo `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SqlOne) Reset()         { *m = SqlOne{} }
func (m *SqlOne) String() string { return proto.CompactTextString(m) }
func (*SqlOne) ProtoMessage()    {}
func (*SqlOne) Descriptor() ([]byte, []int) {
	return fileDescriptor_698b595ef5cec090, []int{3}
}

func (m *SqlOne) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SqlOne.Unmarshal(m, b)
}
func (m *SqlOne) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SqlOne.Marshal(b, m, deterministic)
}
func (m *SqlOne) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SqlOne.Merge(m, src)
}
func (m *SqlOne) XXX_Size() int {
	return xxx_messageInfo_SqlOne.Size(m)
}
func (m *SqlOne) XXX_DiscardUnknown() {
	xxx_messageInfo_SqlOne.DiscardUnknown(m)
}

var xxx_messageInfo_SqlOne proto.InternalMessageInfo

func (m *SqlOne) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *SqlOne) GetData() *SqlInfo {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *SqlOne) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

//修改 (该结构体也用于显示)
type SqlInfo struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Age                  string   `protobuf:"bytes,3,opt,name=age,proto3" json:"age,omitempty"`
	Desc                 string   `protobuf:"bytes,4,opt,name=desc,proto3" json:"desc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SqlInfo) Reset()         { *m = SqlInfo{} }
func (m *SqlInfo) String() string { return proto.CompactTextString(m) }
func (*SqlInfo) ProtoMessage()    {}
func (*SqlInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_698b595ef5cec090, []int{4}
}

func (m *SqlInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SqlInfo.Unmarshal(m, b)
}
func (m *SqlInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SqlInfo.Marshal(b, m, deterministic)
}
func (m *SqlInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SqlInfo.Merge(m, src)
}
func (m *SqlInfo) XXX_Size() int {
	return xxx_messageInfo_SqlInfo.Size(m)
}
func (m *SqlInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SqlInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SqlInfo proto.InternalMessageInfo

func (m *SqlInfo) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SqlInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SqlInfo) GetAge() string {
	if m != nil {
		return m.Age
	}
	return ""
}

func (m *SqlInfo) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

//新增，删除，修改的response
type SqlRes struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Data                 string   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SqlRes) Reset()         { *m = SqlRes{} }
func (m *SqlRes) String() string { return proto.CompactTextString(m) }
func (*SqlRes) ProtoMessage()    {}
func (*SqlRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_698b595ef5cec090, []int{5}
}

func (m *SqlRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SqlRes.Unmarshal(m, b)
}
func (m *SqlRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SqlRes.Marshal(b, m, deterministic)
}
func (m *SqlRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SqlRes.Merge(m, src)
}
func (m *SqlRes) XXX_Size() int {
	return xxx_messageInfo_SqlRes.Size(m)
}
func (m *SqlRes) XXX_DiscardUnknown() {
	xxx_messageInfo_SqlRes.DiscardUnknown(m)
}

var xxx_messageInfo_SqlRes proto.InternalMessageInfo

func (m *SqlRes) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *SqlRes) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *SqlRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

//查询response的list
type SqlSelRes struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Data                 *Data    `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SqlSelRes) Reset()         { *m = SqlSelRes{} }
func (m *SqlSelRes) String() string { return proto.CompactTextString(m) }
func (*SqlSelRes) ProtoMessage()    {}
func (*SqlSelRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_698b595ef5cec090, []int{6}
}

func (m *SqlSelRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SqlSelRes.Unmarshal(m, b)
}
func (m *SqlSelRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SqlSelRes.Marshal(b, m, deterministic)
}
func (m *SqlSelRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SqlSelRes.Merge(m, src)
}
func (m *SqlSelRes) XXX_Size() int {
	return xxx_messageInfo_SqlSelRes.Size(m)
}
func (m *SqlSelRes) XXX_DiscardUnknown() {
	xxx_messageInfo_SqlSelRes.DiscardUnknown(m)
}

var xxx_messageInfo_SqlSelRes proto.InternalMessageInfo

func (m *SqlSelRes) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *SqlSelRes) GetData() *Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *SqlSelRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Data struct {
	UserList             []*SqlInfo `protobuf:"bytes,1,rep,name=userList,proto3" json:"userList,omitempty"`
	Total                int64      `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Data) Reset()         { *m = Data{} }
func (m *Data) String() string { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()    {}
func (*Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_698b595ef5cec090, []int{7}
}

func (m *Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Data.Unmarshal(m, b)
}
func (m *Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Data.Marshal(b, m, deterministic)
}
func (m *Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Data.Merge(m, src)
}
func (m *Data) XXX_Size() int {
	return xxx_messageInfo_Data.Size(m)
}
func (m *Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Data.DiscardUnknown(m)
}

var xxx_messageInfo_Data proto.InternalMessageInfo

func (m *Data) GetUserList() []*SqlInfo {
	if m != nil {
		return m.UserList
	}
	return nil
}

func (m *Data) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func init() {
	proto.RegisterType((*IdInfo)(nil), "aiops.micro.srv.v2.sql.IdInfo")
	proto.RegisterType((*UserRes)(nil), "aiops.micro.srv.v2.sql.UserRes")
	proto.RegisterType((*SqlDetail)(nil), "aiops.micro.srv.v2.sql.SqlDetail")
	proto.RegisterType((*SqlOne)(nil), "aiops.micro.srv.v2.sql.SqlOne")
	proto.RegisterType((*SqlInfo)(nil), "aiops.micro.srv.v2.sql.SqlInfo")
	proto.RegisterType((*SqlRes)(nil), "aiops.micro.srv.v2.sql.SqlRes")
	proto.RegisterType((*SqlSelRes)(nil), "aiops.micro.srv.v2.sql.SqlSelRes")
	proto.RegisterType((*Data)(nil), "aiops.micro.srv.v2.sql.Data")
}

func init() { proto.RegisterFile("sql.proto", fileDescriptor_698b595ef5cec090) }

var fileDescriptor_698b595ef5cec090 = []byte{
	// 333 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x53, 0xcf, 0x4b, 0xc3, 0x30,
	0x18, 0xa5, 0x3f, 0xdc, 0xec, 0x37, 0x10, 0x09, 0x22, 0x45, 0x44, 0x4b, 0x4f, 0x3b, 0x05, 0xd9,
	0x8e, 0xde, 0x64, 0x22, 0x13, 0x51, 0x68, 0xf1, 0xe0, 0xc1, 0x43, 0x6c, 0x3e, 0x25, 0x2c, 0x5b,
	0xd6, 0x24, 0x0e, 0xfc, 0xef, 0x25, 0x69, 0x1d, 0xd3, 0x59, 0xe6, 0xc9, 0xdb, 0x4b, 0xfa, 0xf2,
	0xde, 0xf7, 0x1e, 0x5f, 0x21, 0x31, 0xb5, 0xa4, 0x4b, 0xad, 0xac, 0x22, 0xc7, 0x4c, 0xa8, 0xa5,
	0xa1, 0x73, 0x51, 0x69, 0x45, 0x8d, 0x5e, 0xd1, 0xd5, 0x88, 0x9a, 0x5a, 0xe6, 0x29, 0xf4, 0xa6,
	0x7c, 0xba, 0x78, 0x55, 0xe4, 0x00, 0x42, 0xc1, 0xd3, 0x20, 0x0b, 0x86, 0x51, 0x11, 0x0a, 0x9e,
	0x4b, 0xe8, 0x3f, 0x1a, 0xd4, 0x05, 0x1a, 0x42, 0x20, 0xae, 0x14, 0xc7, 0xf6, 0xa3, 0xc7, 0x64,
	0x0c, 0x31, 0x67, 0x96, 0xa5, 0x61, 0x16, 0x0c, 0x07, 0xa3, 0x73, 0xfa, 0xbb, 0x3e, 0x2d, 0x6b,
	0xe9, 0xd4, 0x0b, 0x4f, 0x26, 0x29, 0xf4, 0xe7, 0x68, 0x0c, 0x7b, 0xc3, 0x34, 0xca, 0x82, 0x61,
	0x52, 0x7c, 0x1d, 0xf3, 0x6b, 0x48, 0xca, 0x5a, 0x4e, 0xd0, 0x32, 0x21, 0x9d, 0xdf, 0x82, 0xcd,
	0x1b, 0xbf, 0xa4, 0xf0, 0x98, 0x1c, 0x42, 0xe4, 0x9e, 0x85, 0xfe, 0xca, 0x41, 0xc7, 0xe2, 0x68,
	0xaa, 0x56, 0xc9, 0xe3, 0x7c, 0x06, 0xbd, 0xb2, 0x96, 0x0f, 0x0b, 0xfc, 0x8f, 0x99, 0x4b, 0xe8,
	0xb7, 0xd4, 0x9f, 0xe5, 0xad, 0x13, 0x84, 0xdb, 0x09, 0xa2, 0xed, 0x04, 0xf1, 0x46, 0x82, 0x5b,
	0x9f, 0xa0, 0xab, 0x75, 0xb2, 0x91, 0x20, 0xd9, 0x39, 0xe0, 0xcc, 0x97, 0x5a, 0x62, 0xa7, 0xdc,
	0xc5, 0xb7, 0x42, 0x4e, 0xbb, 0x0a, 0x99, 0x30, 0xcb, 0x76, 0x9a, 0x3d, 0x41, 0xec, 0x78, 0xe4,
	0x12, 0xf6, 0xdf, 0x0d, 0xea, 0x3b, 0x61, 0x6c, 0x1a, 0x64, 0xd1, 0x5f, 0x8a, 0x5e, 0x3f, 0x20,
	0x47, 0xb0, 0x67, 0x95, 0x65, 0xd2, 0x4f, 0x14, 0x15, 0xcd, 0x61, 0xf4, 0x0c, 0x03, 0xb7, 0x8a,
	0x25, 0xea, 0x95, 0xa8, 0x90, 0xdc, 0xc3, 0xe0, 0x06, 0xad, 0xbb, 0xb9, 0xfa, 0x98, 0x72, 0x72,
	0xd6, 0x25, 0xdf, 0x2c, 0xf6, 0x49, 0xa7, 0x7d, 0xbb, 0xde, 0x2f, 0x3d, 0xff, 0x8b, 0x8c, 0x3f,
	0x03, 0x00, 0x00, 0xff, 0xff, 0xb4, 0x7e, 0x3b, 0x95, 0x2f, 0x03, 0x00, 0x00,
}
